GlacioHack/geoutils

GeoUtils/raster_tools.py, GeoUtils/vector_tools.py
Both raster_tools and vector_tools were attempting to load each other into their module namespaces, resulting in circular dependencies.
Now, the relevant module is only imported within the scope of the method which needs it.
=> Fix circular dependencies bug

.github/workflows/python-app.yml, .readthedocs.yml, README.md, environment.yml, geoutils/georaster.py, geoutils/geovector.py, geoutils/satimg.py, requirements.txt, tests/test_georaster.py, tests/test_satimg.py
Closes #24 
`get_data()` and `set_data()` methods added to the Raster class.
I put a low level check in `set_data` that makes sure new data array is the same shape as the existing one. I'm not sure that addresses the check that @atedstone discussed in his issue - Ted will you review and let me know?
I'm also a bit confused as to how this `set_data()` method conflicts with the purpose of _update(), which seems to update the original file with new data. I'm pretty sure that is distinct from the goal of `set_data()`, but again, @atedstone, let me know.
I changed the tests accordingly and those are passing on my machine.
Note that this will probably break people's existing code that lives outside of GeoUtils.
=> Raster data getter/setter methods

geoutils/georaster.py, geoutils/projtools.py, tests/test_georaster.py, tests/test_projtools.py
To be used for example by Raster.value_at_coords or self.interp.
I need to add tests, but there is an issue with the accuracy of the results, e.g.:
```
from geoutils import georaster as gr
from geoutils import datasets
from geoutils import projtools as pt
img = gr.Raster(datasets.get_path('landsat_B4'))
lat, lon = pt.reproject_to_latlon([img.bounds.left, img.bounds.top], img.crs)
x, y = pt.reproject_from_latlon([lat, lon], img.crs)
x - img.bounds.left
```
=> -5.238689482212067e-10
This yields uncertain outputs if for example included in Raster.value_at_coords. If requesting the value of the top-left pixel, it will actually look for the pixel with column -1 instead of 0.
Any idea @rhugonnet ?
=> Add a function to convert coordinates between two CRS, or from/to latlon

geoutils/georaster.py, tests/test_georaster.py
Resolves #121 
Note that there is also the attribute `self.indexes`. This is always set by the contents of `ds.indexes`. Here, `self.bands` refers uniquely to the band order of `self.data`, only if data has been loaded.
=> add bands attribute to Raster

geoutils/__init__.py
See the rationale in #141.
Example:
```python
r = gu.Raster("...")
v = gu.Vector("...")
img = gu.SatelliteImage("...")
```
=> Simplify import statements

geoutils/geovector.py, tests/test_geovector.py
First off, no tests existed for `geovector.py`!
I created some very simple tests, but these should be improved in the future.
I have added two methods to `Vector`:
* `copy()` just returns a copy of itself. Since Vector is only a wrapper for a gpd.GeoDataFrame right now, this was dead simple.
* `query()` allows for text-based queries to the dataframe. In xdem, this is used to query individual glacier outlines from a larger outlines vector. It would be nice to have this method directly instead of a hacky copy approach done right now.
=> Add `copy()` and `query()` methods to Vector and add `test_geovector.py` file

geoutils/georaster.py, tests/test_georaster.py
As discussed with @adehecq, this functionality may have widespread use, and will be especially useful for a function in the making in `xdem`.
```python
rgb_img = gu.Raster(datasets.get_path('landsat_RGB'))
red, green, blue = img.split_bands()
```
Maybe a `.stack()` method or similar should be added to reverse the functionality of `.split_bands()`?
Unfortunately, I wanted to add a `copy: bool =  False` kwarg to reduce copying, but this is not currently possible. `Raster.from_array()` always returns a copy, which is great in most cases, but maybe something can be done about that in the future? A `copy: bool = True` kwarg for `from_array()` which can be changed in case of memory-sensitive work?
=> Add `split_bands()` method to Raster

geoutils/georaster.py, tests/test_georaster.py
I should have experimented a little more before my previous PR!
As shown in the test, `split_bands(copy=False)` now works as one would expect it to, and `.split_bands(copy=True, subset=0)` can for example be used to only return the red band (instead of copying every band)!
Solves the example in #159.
=> Add copy/no-copy functionality to `split_bands()` and `subset` argument

.github/workflows/python-app.yml, dev-requirements.txt, environment.yml
#163 proposed to only have the non-testing requirements in `environment.yml`. This is implemented with this PR.
Secondly, following the implementation in xdem, I changed the build workflow to use `mamba` instead of `conda` for dependency solving. This is much faster. Below is an example in my fork using mamba (top) and not mamba (bottom):
As you can see, builds should now take less than a third of the time it took before. This is because most of the build process was just conda being bad at resolving dependencies!
Finally, I changed the name of the build workflow from `build-geoutils-dev` to `build` in order to make a nice badge, like in xdem:
[![build](https://github.com/GlacioHack/xdem/actions/workflows/python-package.yml/badge.svg)](https://github.com/GlacioHack/xdem/actions/workflows/p …
=> Separate dev-requirements and improve build workflow

geoutils/georaster.py, tests/test_georaster.py
Something that bugs me about rasterio is that a resampling method cannot be given as a string, but must be given as their enums, which are not even imported by the base rio. This means that cubic spline resampling has to be made with:
```python
import rasterio as rio
import rasterio.warp
img1 = gr.Raster(datasets.get_path("landsat_B4"))
img2 = gr.Raster(datasets.get_path("landsat_B4_crop"))
img1_reproj = img1.reproject(img2, resampling=rio.warp.Resampling.cubic_spline)
```
In this PR, I've added parsing functionality for strings as an alternative to the enums:
```python
img1 = gu.Raster(gu.datasets.get_path("landsat_B4"))
img2 = gu.Raster(gu.datasets.get_path("landsat_B4_crop"))
img1_reproj = img1.reproject(img2, resampling="cubic_spline")
``` …
=> Simplify reproject resampling argument to accept strings

.github/workflows/python-app.yml, environment.yml, tests/test_docs.py
Also, some tests are improved to work better on Windows, and `scipy` was missing from the `environment.yml`.
This was a really hard one!!
=> Add CI for windows, macos and linux, for multiple python versions

geoutils/georaster.py
As mentioned in #178, this will especially help newcomers with little to no GDAL experience. Also, compression should be on by default.
@adehecq  and I discussed what the default compression algorithm should be, and we ended up somewhere between LZW and DEFLATE. @rhugonnet recommended DEFLATE over LZW, so I chose DEFLATE. 
We could easily test different compression algorithms in a future project to find the absolute best default for every use-case, but DEFLATE will definitely do the job for now!
=> Add `compress` and `tiled` arguments for `Raster.save()` and enable compression by default.

geoutils/georaster.py, geoutils/geovector.py, tests/test_georaster.py, tests/test_geovector.py
This branch started out with the aim to fix #176, but it turned out that `Raster.crop()` actually did work as expected!! I did however see that the Vector crop wasn't implemented and that some more fixes could be made:
* `Raster.crop(Vector)` now works.
* `Raster.crop` has an `inplace` argument which is True by default. If False, it will return a new separate Raster.
* `Vector.bounds` and `Vector.crs` now exist.
=> Add support to crop rasters with vectors, and minor other improvements

geoutils/georaster.py, tests/test_georaster.py
Solves #174.
A test is added to validate that no warnings occur in the future.
=> Fix `Raster.info(stats=True)` warning

geoutils/projtools.py, tests/test_projtools.py
This was a change that was waiting for a commit on my computer for some time...
The method merge_bounds takes any of the following: list/tuple of coordinates, Raster objects, rasterio BoundingBox or geopandas GeoDataFrame.
It merges the bounding boxes using either the union or intersection of all.
=> Add a function to merge different bounds

geoutils/georaster.py, geoutils/projtools.py, tests/test_georaster.py, tests/test_projtools.py
Now, Raster.reproject should be closer (if not equivalent) to what gdalwarp would do, when dst_bounds is set i.e.:
- if dst_bounds is set but nothing else, the dst_res and shape are modified to fit dst_bounds
- if dst_bounds and dst_res are set, will enforce dst_res and will adjust dst_bounds accordinly (by up to one pixel)
I think it would be tough to get a complete test suite for all the possible cases, but I did my best! 
I compared the outputs with gdalwarp on a few tests cases and it's the same. Ideally we would compare with gdal for a million cases!
P.S: I don't know what I did wrong again, but my previous PR is also included here...
=> Fix several issues with reproject when dst_bounds is set

.github/workflows/pre-commit.yml, .github/workflows/python-app.yml, .pre-commit-config.yaml, .readthedocs.yml, .relint.yml, CONTRIBUTING.md, README.md, dev-requirements.txt, doc/source/code/raster-basics_open_file.py, doc/source/code/vector-basics_open_file.py, doc/source/conf.py, doc/source/index.rst, doc/source/raster-basics.rst, doc/source/vector-basics.rst, geoutils/__init__.py, geoutils/datasets/__init__.py, geoutils/georaster.py, geoutils/geovector.py, geoutils/geoviewer.py, geoutils/projtools.py, geoutils/satimg.py, setup.py, tests/test_datasets.py, tests/test_docs.py, tests/test_georaster.py, tests/test_geovector.py, tests/test_projtools.py, tests/test_satimg.py
This was a big one!! Up until now, the code style in GeoUtils has been largely inconsistent, where each contributor has more or less had their own style. This PR brings an automatic check to validate the code using a bunch of tools, and a refactor of the entire code-base to adhere to these standards.
* The codebase now uses black and isort to format the code automatically
* An exception to black's strict rules is the 120 character limit instead of 88. This applies for all linters as well
* Incorrectly spelled words in comments and text are now shown as lints (valdate -> validate and so on)
* mypy is running in strict mode, with some exceptions. This means that all functions have to be type-annotated. I've needed to add the `# type: ignore` flag to some places where mypy doesn't understand …
=> Refactor code to adhere to a number of standards

.pre-commit-config.yaml, geoutils/georaster.py, geoutils/geovector.py, tests/test_georaster.py
As was discussed https://github.com/GlacioHack/xdem/issues/145, allowing numpy functions directly on a raster object would be very nice to have (it would just point to self._data):
```python
mean = np.mean(raster)
raster += np.ones_like(raster)
```
This turned out to be a quite simple fix! numpy has the `__array_interface__` which is used for all of their functionalities. So I just added a property that first loads the data if needed and then provides the `__array_interface__` of `self._data`. As you can see in the tests, it seems to work quite well!
=> Add numpy interface

.github/workflows/python-app.yml, dev-requirements.txt, environment.yml, geoutils/georaster.py, setup.py
Motivated in #217.
This is integral for #208  and #216  to work properly!
The solution is to install+import `typing-extensions` for python versions lower than 3.8. This is an official backport of the new typing functions, so it should work as well!
=> Allow `Literal` for python 3.7 and lower

geoutils/georaster.py, tests/test_georaster.py
This is one that I've been missing in many projects!
Many tools work with point clouds, and there's not been a great way to convert a `Raster` (or any other raster-type) into a point cloud. This is for example good for coregistration, as one might not want to load the entire raster.
A point cloud with x/y coordinate and all bands' values is returned.
```python
>>> img = gu.Raster(gu.datasets.get_path("landsat_rgb"))
>>> points = img.to_points(subset=10)
>>> points.shape  # It has the columns ["x", "y", "red", "green", "blue"]
(10, 5)
>>> points[0, :]
array([4.931650e+05, 3.106325e+06, 2.550000e+02, 2.550000e+02, 2.550000e+02])
``` 
A `GeoDataFrame` may be more convenient for some, allowing e.g. easier plotting, CRS conversions and much more.
```python
>>> points_frame = …
```
=> Add `Raster.to_points()` method

.github/workflows/python-app.yml, geoutils/satimg.py, tests/test_georaster.py
This PR includes three minor fixes:
- 8c124a6: When running CI, the output is currently littered with 49 PASSED lines (showing which ones that passed). This is quite unnecessary, as the only interesting information is if they failed or gave warnings! This commit removes the PASSED messages.
- bd73829: @rhugonnet your opinion might be valuable here. Currently, if a `SatelliteImage` is read from disk, `fn_meta` will be `None`, meaning it will try to run `SatelliteImage.__parse_metadata_from_file()`, triggering the "not implemented" warning. In this commit, I've added a check so that the function will not be run if `fn_meta` is None. This consequently removes a ton of test warnings.
- 78dfcd8: This heavily relates to #220. The nodata value has to be set, or else `Raster.reproject()` …
=> Resolve test warnings and make CI output cleaner

geoutils/__init__.py, geoutils/geovector.py, tests/test_geovector.py
- simple function to extract vertices from a geopandas geodataframe (needed for the rest)
- function to create Voronoi polygons from a gpd.GeoDataFrame. These may spread a lot depending on the geometry.
- function to create Voronoi Polygons that are contained within a Polygon
- Vector method to create non-overlapping buffers around each geometries in self, using the previous functions
```
import numpy as np
import matplotlib.pyplot as plt
outlines = gu.Vector(gu.datasets.get_path('glacier_outlines'))
outlines = gu.Vector(outlines.ds.to_crs('EPSG:32645'))
buffer = outlines.buffer_without_overlap(500)
ax = buffer.ds.plot()
outlines.ds.plot(ax=ax, ec='k', fc='none')
plt.show()
```
or with colors to see that the attributes are retained (although some colors are more or …
=> Include Voronoi polygons and method to create non-overlapping buffers

dev-requirements.txt, environment.yml, geoutils/geovector.py, geoutils/spatial_tools.py, setup.py, tests/test_spatial_tools.py
**Issue 1:** stack_rasters was failing when providing an xdem.DEM instance as input, because the class does not allow multiband rasters
**Issue 2:** Progress bar was not displaying when intended, and also not propagated to merge_raster.
Reproducible example:
```
import xdem
dem = xdem.DEM(gu.datasets.get_path("landsat_B4"))
raster = gu.Raster(gu.datasets.get_path("landsat_B4"))
stacked_rasters = gu.spatial_tools.stack_rasters([raster, raster], progress=True)
merged_raster = gu.spatial_tools.merge_rasters([raster, raster])
stacked_rasters = gu.spatial_tools.stack_rasters([dem, dem])
```
=> Fix several issues in spatial_tools.stack_rasters

geoutils/spatial_tools.py, tests/test_spatial_tools.py
When calling `spatial_tools.stack_rasters` or `spatial_tools.merge_rasters`, masked values are converted to NaNs.
Change code so that outputs are properly masked.
**Reproducible example:**
```
import xdem
import numpy as np
raster = gu.Raster(gu.datasets.get_path("landsat_B4"))
raster.set_ndv(255)
raster2 = raster.copy()
raster2.set_ndv(254)
print(np.min([raster.data, raster2.data]))
stacked_rasters = gu.spatial_tools.stack_rasters([raster, raster2], progress=True)
merged_raster = gu.spatial_tools.merge_rasters([raster, raster2])
print(np.min(stacked_rasters.data))
print(np.min(merged_raster.data))
```
=> Fix issue with merge_rasters creating NaNs

geoutils/georaster/raster.py, tests/test_georaster.py
I think 'nearest' should not be the default resampling algorithm in reproject. For non integer warping, it will create artificial shifts between the two rasters. 
Bilinear is the safest option as it is relatively fast, preserves range and will have an effect even for subpixel shifts.
Any thought against that?
=> Set default resampling to bilinear instead of nearest in reproject

geoutils/georaster/raster.py, setup.py, tests/test_georaster.py
The attributes inherited from rasterio's DatasetReader were not clearly defined, which makes it more difficult for tests, especially in child classes like in xdem.
Ideally, the docstring of the Raster class should be checked so that the list there matches the actual default list.
=> Clearly define default rio attributes

.github/workflows/python-app.yml, README.md, dev-environment.yml, dev-requirements.txt, environment.yml, geoutils/examples.py
This PR:
- Adds the workflow for Coveralls;
- Adds a `dev-environment.yml` file to facilitate the installation for developers and feed to CI, to have the exact same environment locally;
- Adds `pytest-xdist` in development dependencies to distribute `pytest` on several CPUs when possible;
- Changes the use of `TemporaryDirectory()` as a context manager in `examples.py` to avoid failures during CI tests.
=> Add test coverage from Coveralls in CI

dev-environment.yml, dev-requirements.txt, environment.yml, geoutils/georaster/raster.py, tests/test_georaster.py, tests/test_geovector.py
This PR corrects the behaviour of `Raster.data.setter`, which is directly used by `Raster.__init__()` or `Raster.from_array()` to construct/update the `data` attribute. It also adds tests to ensure this behaviour will be constant.
**The previous behaviour was:**
1. A unmasked `np.ndarray` or a `np.ma.masked_array` can both be used to set a new `data`,
2. The shape was checked: if 2D broadcast to 3D, otherwise an error was raised,
3. The dtype was checked: if it didn't match the previous `dtype`, an error was raised.
4. The array was simply cast to a `np.ma.masked_array` with `fill_value` set from the `nodata`.
**The new behaviour modifies point 4. Now:**
- If the array is unmasked and has non-finite values, a mask of these non-finite values is created and passed to `np.ma.masked_array`. …
=> Improve `data.setter` of `Raster` for consistent array output

.pre-commit-config.yaml, geoutils/georaster/raster.py, tests/test_georaster.py
This PR adds a **nodata-aware array interface** to work with `Raster` objects and their subclasses. **All of the ~90 universal functions of NumPy are now supported** (see ufuncs: https://numpy.org/doc/stable/reference/ufuncs.html), **and also ~25 NumPy array functions** defined on a per-need basis (such as np.min, np.max, np.mean, np.median, np.std, np.var, np.percentile, np.quantile). All these functions are wrapped in a way that accounts for possible `nodata` in `Raster.data`.
In #210, we added `__array_interface__` as a property to perform operations on `Raster` classes as if on array. However, this interface points to the array of the masked array `.data.data`, and therefore gives inconsistent results depending on `nodata` values.
For example:
```python
np.min(raster.data) # minimum …
```
=> Improve array interface of `Raster` for consistency with `np.ma.masked_array` operations

geoutils/georaster/raster.py, tests/test_georaster.py
As discussed many times, it is much more familiar for many people to work with classical arrays rather than masked arrays. Right now, we have to use the `gu.spatial_tools.get_array_and_mask` method to convert between the two, which is a bit unintuitive. Additionally, the `get_array_and_mask` method is made to work with any type of input to homogenize the behaviour of some functions. This is not needed when working with a `Raster` object that always has the same `.data`.
In this PR, we add the `Raster` class method `get_nanarray` to return a NaN array, with argument `return_mask` (defaults as `False`) to possibly the original mask of valid data as well. 
The behaviour is the following:
- The NaN array corresponds exactly to `Raster.data.filled(fill_value=np.nan).squeeze()`, i.e. the data …
=> Add `get_nanarray` method

geoutils/georaster/raster.py, geoutils/geoviewer.py, geoutils/spatial_tools.py, tests/test_georaster.py
This PR homogenizes the getter and setter functionality related to `nodata` and adds more exhaustive tests.
In details, this PR:
- Renames `set_ndv()` into `set_nodata()`, and all other occurences of "ndv" to "nodata", in order to match the `nodata` naming of `rasterio` and avoid the confusion of having "ndv" and "nodata" standing for the same thing,
- Corrects the behaviour of `update_array` in `set_nodata()`,
- Adds the `update_mask` argument to `set_nodata()`,
- Adds a `nodata.setter` method that calls `set_nodata()` with default parameters,
- Improves or adds tests for `set_nodata` and `nodata.setter`,
- Moves the nodata-related functions/class methods together in the file (among others, mypy request the getter/setter method to follow each other).
The old behaviour was:
- The argument …
=> Modify `set_nodata` behaviour, improve related warnings and tests

geoutils/georaster/raster.py, geoutils/misc.py, tests/test_georaster.py, tests/test_satimg.py
This PR modifies the behaviour of `__eq__` to have a rigorous equality check between Raster objects.
As a result, a certain number of test failed linked to arithmetic operations, and thus a correction was made to `_overloading_check` and `data.setter` to avoid inconsistencies that were created in the masked arrays. Then, tests relying on `__eq__` were updated to be more robust. 
Additionally, the custom function `gu.misc.array_equal` initially introduced for back-compatibility and for which the behaviour was not clearly defined to all (it only checked valid data, but did not compare unmasked `data`, the `mask` themselves, or the `dtypes` as some of us expected) is now deprecated as similar functionalities exist in NumPy: `np.array_equal(equal_nan=True)`, or `np.ma.allequal`, or in our new …
=> Fix `__eq__`, make arithmetic operations fully consistent with masked arrays, deprecate `gu.misc.array_equal` and bug fixes

tests/test_misc.py
All in the title, mirrors the test in xDEM.
=> Add test for deprecator function

.pre-commit-config.yaml, geoutils/geovector.py
Our current build is not passing because of `pre-commit` issues that arose since CI last run for #321 (sometime in the last two weeks). 
This PR solves those by upgrading packages, and also adding the black profile to `isort`.
After the upgrade, there is only two new mypy errors related to `__init__`  calls used in `geovector`. Those are not crucial (related to potential subclassing), so they are ignored for now.
=> Upgrade `pre-commit`

.github/get_yml_env_nopy.py, geoutils/misc.py
To match the issues found in https://github.com/GlacioHack/xdem/pull/320, in case GeoUtils relies more on `pip` in `environment.yml` and `dev-environment.yml` in the future.
The "pop" was not happening at the right line, and some functions were listing the dictionary key instead of values.
=> Fix `pip` dependency listing in CI

.pre-commit-config.yaml, geoutils/satimg.py, tests/test_satimg.py
Adds a condition for the new nomenclature of PGC DEMs in `parse_metadata_from_fn` of `satimg.py`, as well as associated tests.
Resolves #332
=> Update SETSM product filename metadata parsing in `SatelliteImage` class

geoutils/georaster/raster.py, geoutils/geovector.py, geoutils/projtools.py, geoutils/spatial_tools.py, tests/test_georaster.py, tests/test_geovector.py, tests/test_spatial_tools.py
This PR updates the `get_geoprojected_bounds` function, moving its core to `projtools` to make it consistent and accessible for both `Raster` and `Vector` classes. 
Then, it adds the same options in `Vector.crop()` than for `Raster.crop()` (= passing another `Raster`, `Vector` or a list of bounds). 
Finally, it implements the `__getitem__` (= `[]`) method for `Raster` and `Vector`, which calls their underlying `crop` functionality (= subsetting), as suggested previously by @erikmannerfelt.
```python
rst = Raster(fn_rst)
vec = Vector(fn_vec)
rst = rst[vec]
```
Other than that, several bug fixes and test additions.
Several things:
- We could add the option of provides `slice` objects, which would then be used on `self.data` for `Raster` (subsetting `np.MaskedArray` in 2D) and `self.ds` on …
=> Subscript-crop `Raster` or `Vector` by bracket call `[]`, consistency and bug fixes

geoutils/georaster/raster.py, geoutils/geovector.py, geoutils/projtools.py, tests/test_georaster.py, tests/test_geovector.py, tests/test_projtools.py
This PR adds a `proximity()` function to the `Vector` and `Raster` classes that mirrors GDAL's proximity not implemented in `rasterio` (https://github.com/rasterio/rasterio/issues/319), and a `buffer_metric()` method for the `Vector` class to avoid the trouble of reprojecting from geographic system, buffer, than reverse-projecting, based on finding a local UTM zone.
It also adds a `Raster` method `equal_georeferenced_grid` to check if two rasters have the same georeferencing.
The proximity is computed using `scipy.distance_transform_edt` (https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html).
The functioning is as follows:
- For `Raster` classes, the proximity can be either computed directly from target values of the array `self.data`, or from a …
=> Add `proximity` and `buffer_metric` functionalities with `metric` option based on finding local UTM 

.pre-commit-config.yaml
One-line PR to update the `isort` version, that otherwise keeps failing on build when trying to run `pre-commit` on all other PRs opened or ongoing.
=> Fix `isort` version in `pre-commit`

geoutils/georaster/raster.py, geoutils/geovector.py, geoutils/misc.py, geoutils/spatial_tools.py, tests/test_georaster.py, tests/test_geovector.py
Resolves #239 and adds tests.
Additionally, updates the list of resampling algorithms of `rasterio` from `rio.warp.Resampling` to `rio.enums.Resampling`, and gets the names using `.name` instead of `str()`, which fails in Python `3.11` (opened issue: https://github.com/rasterio/rasterio/issues/2750).
=> Add support for `pathlib.Path` object as `filename` of Raster and Vector

.pre-commit-config.yaml, geoutils/georaster/raster.py, tests/test_georaster.py
This PR adds tests for the `value_at_coords` function, adds the functionality of passing an array-like object of coordinates, and fixes minors bugs.
It looks like  more changes than there actually is in the "Files changed". Owing to shifting blocks of code in `value_at_coords` to be either in or out of the loop (added for array-like).
There's also a setup bug with `isort` that they recommend to fix by upgrading to `5.12.0` (will need the same in xDEM): moved to #343.
Resolves #324
Resolves #245
=> Fix bugs and write tests for `Raster.value_at_coords()`

geoutils/georaster/raster.py, geoutils/geoviewer.py, tests/test_georaster.py
This PR fixes the color bar alignment with the main plot when using `Raster.show()` and tests that the cbar and main plot heights are approximately equal. 
Additional changes:
- Add alpha parameter for plot and cbar to `Raster.show()`
- Rename `cb` to `cbar` to match matplotlib conventions.
=> Fix cbar alignment in `Raster.show`

geoutils/georaster/raster.py, tests/test_georaster.py
Resolves #354 (now provides directly the transform when a reference raster is passed)
Adds a test that fails with the previous behaviour
The issue is only fixed when passing a reference to match! 
Still present when passing `dst_bounds` and `dst_res` (or `dst_size`) manually... Seems to arise from floating precision in transform estimation of Rasterio. Not sure how we could fix that.
=> Fix `Raster.reproject()` floating precision of output `res` on large grids

.github/workflows/python-app.yml, dev-environment.yml, doc/source/conf.py
Mirroring xDEM's PR: https://github.com/GlacioHack/xdem/pull/364
=> Fix inheritance diagram rendering in documentation

README.md, doc/source/core_py_ops.md, geoutils/raster/raster.py, tests/test_doc.py
Renaming `test_docs` into `test_doc` for consistency, and fixing minor errors in documentation.
=> Minor documentation fixes

tests/test_doc.py
We have a failing of coverage push to Coveralls on the main branch (dropped to 0%). While it wasn't the case on other PRs. Can't seem to be able to fix it by rerunning GitHub Actions of the main branch.
Let's try here.
=> Fix `coverage` failure

dev-environment.yml, environment.yml
=> Force `geopandas>0.12` to avoid import failure

doc/source/api.md, geoutils/raster/multiraster.py, tests/test_multiraster.py
This PR:
- Adds the support for different raster CRS in `merge_rasters` and `stack_rasters` (only a few lines to change),
- Adds a test case,
- Adds both functions to the API,
- Streamlines the docstring of these functions.
Resolves #371
=> Allow different `crs` for functions in `multiraster.py`

dev-environment.yml, doc/source/conf.py, environment.yml, geoutils/vector.py, tests/test_vector.py
Mirroring https://github.com/GlacioHack/xdem/pull/388
And adding some new exceptions for GeoPandas functions supported, and a new `kwargs` argument to `Vector.dissolve()`
Forced `numpy=1.24` and opened #381
=> Report MySt-NB failures as error in Sphinx build

geoutils/raster/raster.py, tests/test_raster.py
Trying to properly force this behaviour for the `Mask` class.
Resolves #379
=> Fix save with "uint8" `dtype` for `Mask` class

dev-environment.yml, environment.yml, geoutils/raster/raster.py, tests/test_raster.py
In short:
- Replacing `np.find_common_dtypes` that is deprecated: to get the same behaviour, now using `np.promote_dtypes` in a `try`/`except` to catch promotion errors with datetimes and return an object dtype (see https://numpy.org/devdocs/release/1.25.0-notes.html#deprecations),
- Ignoring `int64` and `uint64` casting rules in `ufunc` tests, which were recently added.
Resolves #381
=> Update with NumPy 1.25

geoutils/projtools.py, geoutils/raster/raster.py, tests/test_raster.py
This PR:
- Resolves #377 by adding a `distance_unit` argument to `Raster.shift()` who can be either "pixel" or "georeferenced" (mirroring the `proximity()` functionality),
- Resolves #376 by removing `skip_equivalent`.
=> Small fixes

.pre-commit-config.yaml, geoutils/_typing.py, geoutils/projtools.py, geoutils/raster/array.py, geoutils/raster/multiraster.py, geoutils/raster/raster.py, geoutils/raster/sampling.py, geoutils/raster/satimg.py, geoutils/vector.py, mypy.ini, tests/test_projtools.py, tests/test_raster.py, tests/test_sampling.py
This PR adds the NumPy plugin for `mypy` type checking.
NumPy arrays now have to be statically typed with certain dtypes and shapes (https://numpy.org/devdocs/reference/typing.html).
To keep it simple, I ignored the shape and only defined types (like was done in xDEM, still raised more than 100 errors on `mypy`) and introduced the following types for GeoUtils:
- `NDArrayNum` is a numerical ND array, i.e. with floating or integer type,
- `NDArrayBool` is a boolean ND array,
- `MArrayNum` is a masked numerical ND array,
- `MArrayBool` is a masked boolean ND array.
We can change those names if they don't feel like the best, it's easy as it's just a refactor. Eventually, we could even add the shape to have even more robust type-check in all functions (both here and in xDEM).
**Note: using an …
=> Refine typing with NumPy plugin of `mypy`

geoutils/vector.py, tests/test_vector.py
Before the major refactoring of Shapely a year ago, `shapely.Geometry` did not exist. But we've been using for (static and dynamic) type checking in functions during the past year. It all passed in CI, as older versions of Shapely were never used.
As it's just about editing 4/5 types, I think we modify them all to the old `shapely.geometry.base.BaseGeometry` syntax so that we can be backwards-compatible for a bit longer! :slightly_smiling_face: 
Resolves #391
=> Backward-compatiblity with Shapely < 2.0

geoutils/raster/raster.py
Helps on https://github.com/GlacioHack/xdem/issues/404
=> Add `np.abs` and `np.absolute` to supported NumPy array functions in `Raster`

tests/test_vector.py
Otherwise it'll become impossible to maintain across different Python versions!
The warnings will help us add new methods as they come in.
=> Make GeoPandas tests for new functions/args raise warning and not fail in CI

setup.cfg
Trying to fix the `conda-forge` build, getting the same issue as here: https://github.com/GlacioHack/xdem/issues/394
Likely triggered by the changes in #398
=> Declare `geoutils.raster` sub-package explicitly

.github/workflows/python-app.yml, CONTRIBUTING.md, dev-environment.yml, environment.yml, setup.cfg, tests/test_raster.py
It's been a year since Python 3.11 is out, we can now safely add support for it (most of us probably already work on it in our local environments, as we didn't pin an upper limit on Python version in env files).
=> Add support for Python `3.11` and remove `3.8`

.github/workflows/pre-commit.yml, dev-environment.yml
Mirrors https://github.com/GlacioHack/xdem/pull/451
Also updates action version numbers for `pre-commit` (failing during CI otherwise), as done in https://github.com/GlacioHack/xdem/pull/411)
Fixes the wrong rendering of the documentation since the pydate-sphinx-theme 0.14 by forcing 0.13 (see issue https://github.com/executablebooks/sphinx-book-theme/issues/761).
We should be able to update soon, sphinx-book-theme is catching up with a pre-release: https://github.com/executablebooks/sphinx-book-theme/releases.
Opened https://github.com/GlacioHack/xdem/issues/452
=>  Fix documentation rendering due to Pydata theme update

.github/workflows/python-publish.yml, pyproject.toml, requirements.txt
=> Fix `pip` install with `setuptools-scm` versioning

.github/workflows/python-publish.yml
=> Force fetch depth of 0 for setup to work on Github Actions

geoutils/misc.py, tests/test_misc.py
See more details on the issue here: https://github.com/GlacioHack/geoutils/issues/427#issuecomment-1886997583
Was failing locally but not in CI because of link between `git` and `setuptools_scm` for versioning. Now using `Version` objects to have things consistent everywhere! (easy to change our deprecated mechanism in the future if we want to, by extracting a different major/minor/micro version from the Version object :smile:)
Tested locally with:
- Classic local version due to commits: ```__version__ = version = '0.0.18.dev4+g90460bf'```
- Pre-release versions that are more tricky due to `rc` suffix attached to last version number: ```__version__ = version = '0.0.17rc2.dev1+gef706f8'```
Both passing!
Resolves #427
=> Fix `test_deprecate` to work with `setuptools_scm` versions

geoutils/raster/raster.py, tests/test_raster.py
=> Fix for issue #409 and #407

doc/source/quick_start.md, doc/source/raster_class.md, doc/source/vector_class.md, examples/handling/georeferencing/crop_raster.py, examples/handling/georeferencing/crop_vector.py, geoutils/projtools.py, geoutils/raster/multiraster.py, geoutils/raster/raster.py, geoutils/vector.py, tests/test_multiraster.py, tests/test_raster.py, tests/test_vector.py
**This PR creates breaking changes to the API**
Resolves part of #432:  `Raster.crop()` is now `inplace=False` by default. This aligns its functionality with `Raster.reproject()` and with other projects more generally such as xarray.
The PR also fixes a bug in `test_projtools:test_utm_to_epsg`. A KeyError was being returned by `proj_tools.utm_to_epsg()`:
```python 
with pytest.raises(TypeError):
pt.utm_to_epsg({"utm": "10N"})  # type: ignore
```
This is now fixed by requiring a `str` type in `utm_to_epsg()`, allowing all tests to pass locally on my machine.
=> Change default behaviour of crop to inplace=False

dev-environment.yml, examples/analysis/point_extraction/reduction.py, tests/test_doc.py
Attempts to fix an issue only referenced on xdem: https://github.com/GlacioHack/xdem/issues/316.
- Fix an issue of shapely backward compatibility in one of the examples 
- Re-enable `test_doc.py` for Mac -> The test now passes ! 🥳 (I'm not sure if it's related to my change or it was fixed earlier). 
- Remove the fixed version for pydata-sphinx-theme which was causing a bug with the logo (see #351)
- Doc was also building on Windows, until the new CLI doc section (#418)
Raised issue #442 for the Windows problem.
=> Attempt to fix issue with doc building on Mac/Windows

doc/source/raster_class.md, examples/analysis/point_extraction/interpolation.py, examples/handling/georeferencing/reproj_raster.py, examples/handling/georeferencing/reproj_vector.py, geoutils/projtools.py, geoutils/raster/multiraster.py, geoutils/raster/raster.py, geoutils/raster/sampling.py, geoutils/vector.py, tests/test_multiraster.py, tests/test_projtools.py, tests/test_raster.py, tests/test_sampling.py, tests/test_vector.py
**This PR causes breaking changes to API**
Resolves the rest of #432. 
This PR proposes to regularise the grammar around the word sample and its derivatives.
- When the intention is to return a (random) sample, the term `sample` is used. Previously, `subset` or `subsample` were both used to denote this purpose.
- `downsample` or `upsample` defines a change in a Raster's resolution.  The more generic term is `resample`, but the use of a specific direction is preferred. Try not to use `resample` as this has connotations of towards `reproject`.
- The terms `subset` and `subsample` refer to an contiguous portion of data (e.g. an `x*y` window of a `Raster`, specific bands of a `Raster`, or `row n...row m` of a `Vector`), without a change in resolution. I am regularising to `subset`.
=> Homogenize API arguments

geoutils/raster/raster.py, tests/test_raster.py
Related to #357 and #212.
Re-organized the way `Raster.reproject` works :
- the part that handles the logic of finding the correct output goereferences has been moved to a separate (hidden) function `_get_reproject_params`. It relies now on rasterio functions (`rio.warp.calculate_default_transform` and `rio.transform.from_bounds`) only instead of making our own maths. 
- `reproject` now takes care only of the actual reprojection and handling the data
- re-organized the logic in reproject a bit and improved comments
- improve a test in TestRaster::test_reproject regarding the floating point issue
- updated a test in TestMask::test_reproject that was not actually requiring reprojection to run
- overall, improved logic in test_reproject (testing of match reference should come last instead of …
=> Updates in Raster.reproject: fix bug, simplify code and improve tests

geoutils/raster/raster.py, tests/test_raster.py
Resolves #408.
Phew, this was a tough one! It turns out that `Raster.crop()` was not very thoroughly implemented in the case when data is not loaded. A few things to pay attention to:
- one needs to create a Window using the on-disk transform, not the in-memory one, otherwise we're just reading the wrong bits!
- calling `rio.DatasetReader.read` is actually more complex than it seems when either of cropping or downsampling need to be executed. One needs to make sure that Window and out_shape really match. The window shape can actually be misleading because with option `boundless=False` (default), the window will be cropped if it extends beyond the raster extent. It makes sense after all...
Doing so, I noticed that our downsampling functionality is actually slightly wrong, see issue #447. …
=> Solves #408 (incompatibility between crop and downsampling)

geoutils/raster/raster.py, tests/test_raster.py
- Resolves #451,
- Tests for downsampling improved
=> Fix #451 and improve tests for downsampling

bin/geoviewer.py, examples/handling/georeferencing/reproj_raster.py, examples/io/open_save/read_raster.py, geoutils/raster/raster.py, geoutils/raster/satimg.py, tests/test_raster.py
Ongoing
Resolves #441 
Resolves #449 
Resolves #445
Also re-orders some arguments of `reproject` (most used to least used), to make access easier. 
Left to-do:
=> Additional homogenization and fixes of argument names

geoutils/raster/raster.py, geoutils/vector.py, tests/test_raster.py, tests/test_vector.py
This PR:
- Adds a consistent error message across operations requiring two raster or one raster and one array that are aligned (arithmetic, NumPy array interface, indexing, index assignment),
- Removes the cropping behaviour of [] and makes it fully consistent with NumPy (allows any index supported by NumPy: integer, slices "1:5", ellipsis "...", or new axes.
- Improves significantly the tests for all errors raised and new behaviour.
Mysterious behaviour of NumPy makes the tests fail only on 4 specific array functions, everything else passing... :thinking: 
Resolves #433
Resolves #431
Opened #457
=> Improve error messages and make `Raster` indexing/assigment NumPy compatible

geoutils/raster/raster.py, tests/test_raster.py
- solves #453 
- fixes an issue with reproject not enforcing bounds in some cases due to floating point precision (see [issue](https://github.com/rasterio/rasterio/issues/3016) raised in rasterio). Extracted window need to be rounded to nearest integer rather than up.
Weirdly the second change does not make any difference for tests. I guess in all tested cases, the rounding does not make any difference. This was probably an edge case that I encountered.
Not sure if there is any test to add for this...
=> Two fixes in Raster.reproject

doc/source/about_geoutils.md, doc/source/cli.md, doc/source/code/about_geoutils_sidebyside_raster_geoutils.py, doc/source/code/about_geoutils_sidebyside_raster_rasterio.py, doc/source/code/about_geoutils_sidebyside_vector_geopandas.py, doc/source/code/about_geoutils_sidebyside_vector_geoutils.py, doc/source/core_composition.md, doc/source/core_match_ref.md, doc/source/feature_overview.md, doc/source/how_to_install.md, doc/source/index.md, doc/source/proj_tools.md, doc/source/quick_start.md, doc/source/vector_class.md, examples/handling/georeferencing/crop_raster.py, examples/handling/georeferencing/reproj_raster.py, examples/handling/georeferencing/reproj_vector.py, examples/io/import_export/from_array.py, examples/io/open_save/read_raster.py, examples/io/open_save/read_vector.py, tests/test_doc.py
We're nearly at `v0.1`!! The final touches on the documentation :slightly_smiling_face: 
(There isn't actually many changes, it's just that one doc page was renamed)
Here's the new doc: https://geoutils-rhugonnet.readthedocs.io/en/update_quickstart/
This PR:
- Turns the old "Quick start" (that was far too long, but valuable) into a new page "Feature overview" (with almost no change), for users that want more details on all features centralized in a starting page,
- Adds a new "Quick start" that consists of a single code cell show-casing a short example with a couple core functionalities, and the links to Gallery examples at the bottom,
- Updates some statements at the landing page + simplifies the page (removes the long description that came first, felt a bit too much), and removes the …
=> Update documentation for `v0.1`: Index, Quick start and Feature overview

doc/source/about_geoutils.md
Reported code lines that displayed in the "About GeoUtils" page were wrong due to last-minute modifications of the code, now fixed.
=> Fix code lines in side-by-side examples of "About GeoUtils"

.github/workflows/pre-commit.yml, doc/source/conf.py, doc/source/raster_class.md, examples/analysis/point_extraction/interpolation.py, geoutils/raster/raster.py, setup.cfg, tests/test_raster.py
This PR:
- Makes the behaviour of `interp_points` consistent between equal and regular grid by using both `map_coordinates` and `interpn` from SciPy depending on the grid,
- Removes the default `prefilter` argument of `map_coordinates` that created large data gaps,
- Corrects the `method` argument for `map_coordinates` by mapping it into an `order` argument,
- Adds detailed tests with synthetic data to ensure all results are consistent, in addition to the ones existing in `test_xy2ij`.
Resolves #483 
TO-DO:
=> Make `interp_points` robust to non-equal grids and impractical default SciPy arguments

geoutils/raster/raster.py
The `_repr_html_` of `Raster` had the same exception as the overridden `Mask` class, and didn't show the nodata value. 
Resolves #496
=> Fix nodata not appearing in representation of `Raster`

bin/geoviewer.py, tests/test_geoviewer.py
In `geoviewer.py`, when setting a colormap with the "_r" suffix, an error was raised. This is fixed by this PR and the tests have been added to check this in the future.
=> Fix error checking colormap in geoviewer.py

geoutils/raster/raster.py, tests/test_raster.py
This PR adds `Raster.from_xarray()` to create a raster from an Xarray dataset (this loads the data, in the future will be able to cast functions directly on the Xarray object through #446).
Correct the behaviour of `to_xarray()` which was not converting the data to floating when converting, and not masking nodata values (as default was `False` for reading mask in `open_rasterio()`), leading to unmasked nodata values for integer raster types. Now converts to floating by defaults to mask properly as NaNs (only way of masking with Xarray).
Additionally, this function adds two new arguments to `Raster.raster_equal()`: `strict_masked` and `warn_failure_reason`. The former allows to check for less strict equality regarding the mask (masked cells can have different underlying values, as those …
=> Add `Raster.from_xarray()` to create raster from a `xr.DataArray`

doc/source/api.md, doc/source/raster_class.md, examples/handling/interface/topoints.py, geoutils/raster/array.py, geoutils/raster/raster.py, geoutils/raster/sampling.py, geoutils/vector.py, tests/test_raster.py, tests/test_sampling.py
This PR improves `Raster.to_pointcloud()` in terms of argument consistency, modularity, and makes its subsampling functionality only returns valid values (while before it returned any random sample) to also be consistent with other subsampling methods.
Additionally, this PR adds a non-public `Raster._load_only_mask()` function called by a new public function `Raster.get_mask()`, which allows to get the nodata mask without loading the array into memory. This is used in `.to_pointcloud()` to perform sampling of only valid values without loading the array in memory :smile:.
The PR also adds a lot of tests!
This PR:
- Renames `Raster.to_points()` into `Raster.to_pointcloud()` for consistent naming in preparation for #492,
- Define a main `data_column_name` argument for …
=> Make `Raster.to_pointcloud()` modular and add `Raster.get_mask()` for memory-efficient operations requiring mask

setup.cfg
Somehow `config.ini` was copied by `setuptools` for pip but not for conda, trying by declaring it explicitly.
=> Add `config.ini` to package data for `setuptools`

geoutils/raster/raster.py, tests/test_raster.py
Was already pretty well tested through `test_load_only_mask`, but now we know it's 100% consistent for sure.
Resolves #525
=> Add tests for `Raster.get_mask`

doc/source/about_geoutils.md, doc/source/api.md, doc/source/core_array_funcs.md, doc/source/core_py_ops.md, doc/source/feature_overview.md, doc/source/mask_class.md, doc/source/raster_class.md, geoutils/raster/raster.py, tests/test_raster.py, tests/test_satimg.py
Having `dtypes` as a tuple is effectively never used, even in Rasterio if I'm not mistaken, like for `nodata`.
Having a single value makes things much more straightforward for the user (and us).
Resolves #520
=> Refactor `Raster.dtypes` tuple to a `Raster.dtype` string

tests/test_raster.py
=> Fix `interp_points` test precision with SciPy 1.13.0

.github/workflows/python-tests.yml, geoutils/raster/raster.py, geoutils/raster/satimg.py, tests/test_raster.py
This PR fixes the fact that `set_nodata` was circumvented during `from_array()` creation, making the behaviour fully consistent for checking nodata input and setting. 
Additionally, for practicality, it adds a `cast_nodata` boolean argument to `from_array()` defaulting to `True` which re-casts the input `nodata` to the default of the array type, if the nodata value was incompatible with the input array type.
The impact of this last change was actually much less of a bigger than I thought, because all integer nodata values are compatible with floating array types and the other direction rarely happens. There is almost no NumPy operations that convert from `float` to `int` (even operations like floordiv keep the output a float even if the output of the operation could technically be …
=> Make `nodata` casting consistent based on new array type

examples/analysis/point_extraction/interpolation.py, examples/analysis/point_extraction/reduction.py, examples/io/import_export/from_array.py, geoutils/raster/raster.py, geoutils/raster/sampling.py, tests/test_array.py, tests/test_projtools.py, tests/test_raster.py, tests/test_sampling.py, tests/test_satimg.py
For durability, and was creating some RAM issues for choice without replacement on large arrays. Removed `np.random.RandomState` input type who was just for legacy seeds which we don't need. (more details in https://github.com/GlacioHack/xdem/pull/511)
Resolves #536
=> Remove any use of legacy NumPy random number generator

.github/workflows/python-tests.yml
=> Temporarily pin `coverage` version in CI for `coveragepy-lcov` to work

geoutils/raster/raster.py, tests/test_raster/test_raster.py
Good to keep the flexibility, and needed to facilitate https://github.com/GlacioHack/xdem/pull/531
=> Add `skip_nodata` argument to `Raster.to_pointcloud`

geoutils/raster/raster.py, tests/test_raster/test_raster.py
This PR adds a function `Raster.from_pointcloud_regular` to convert a point cloud on a regular grid into a raster, with tests.
=> Add `Raster.from_pointcloud_regular` to reconstruct a raster from a point cloud

geoutils/raster/raster.py
To use for other functionalities consistently. Linked to #539
=> Wrap transform shift into function outside of `Raster` class

doc/source/raster_class.md, examples/analysis/point_extraction/interpolation.py, geoutils/raster/raster.py, tests/test_raster/test_raster.py
This PR adds small fixes and optimization for point cloud functions.
Resolves #550
Opened #551
=> Small fixes and optimizations for `to_pointcloud` and `interp_points`

geoutils/raster/raster.py, tests/test_raster/test_raster.py
An error had made its way through the test because the synthetic DEM coordinates started on (0,0)!
In practice this option of the algorithm was never used because the grid is almost always of equal resolution (Xres=Yres). As `map_coordinates` is faster, we could actually test if the interpolated results still match for different X/Y res, and remove `interpn` entirely if that is the case, but I'm not sure...
=> Fix `interpn` option of `interp_points`

geoutils/pointcloud.py, geoutils/raster/raster.py, tests/test_pointcloud.py
=> Add point cloud gridding

doc/source/conf.py
Mirrors the change in https://github.com/GlacioHack/xdem/pull/531, makes it much easier to debug notebook execution errors (from the `.md` files of the documentation interpreted by `myst-nb`) only happening in CI and not locally.
=> Show full traceback on notebook execution error

tests/conftest.py
Hopefully a sufficient hack to resolve #545
=> Run Dask-delayed tests last to avoid asynchronous teardown errors

geoutils/raster/delayed.py, geoutils/raster/raster.py, geoutils/vector.py, tests/test_raster/test_raster.py, tests/test_vector.py
Turns out `Vector.translate` already existed (from Geopandas), so renaming Raster method to match instead.
Resolves #569
=> Rename `Raster.shift()` into `Raster.translate` and add `inplace` argument to `Vector.translate`

geoutils/raster/raster.py
Resolves https://github.com/GlacioHack/geoutils/pull/565#discussion_r1637692066
=> Fix padding issue in `Raster.info()`

doc/source/raster_class.md, examples/analysis/point_extraction/reduction.py, geoutils/raster/raster.py, tests/test_raster/test_raster.py
=> Refactor `value_at_coords` into `reduce_points` and fix NaN behaviour

doc/source/conf.py, doc/source/core_lazy_load.md, doc/source/geotransformations.md, doc/source/quick_start.md, doc/source/vector_class.md, geoutils/raster/multiraster.py, geoutils/raster/raster.py
This PR fixes two sphinx warnings due to line indent in docstrings.
It also changes the default behaviour for warning raising in a notebook cell to "warn", to catch unintended warnings/errors raised by notebook cells during documentation build. Cells that are expected to show a warning/error need to be overridden locally using the `output_stderr: show` setting.
Resolves #592
=> Fix documentation warnings

geoutils/raster/multiraster.py, tests/test_raster/test_multiraster.py
The `resampling` argument was not passed to `reproject()` in `stack_rasters`.
Added new tests that ensure it is done consistently now.
Resolves #599
=> Fix resampling not being passed to `stack_rasters` and add tests

geoutils/raster/multiraster.py, tests/test_raster/test_multiraster.py
Bug fixed, and new tests added largely based on the examples provided by @axeldolce in #608 
Resolves #608
=> Fix bug for raster with nodata equal to 0 in `stack_rasters`

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pip-checks.yml, doc/source/conf.py, doc/source/index.md, doc/source/sphinxext.py, setup.cfg
=> Improve resolution of Sphinx-Gallery figures and pin max Python version for pip

.github/workflows/pip-checks.yml, .github/workflows/python-publish.yml, .github/workflows/python-tests.yml, CONTRIBUTING.md, dev-environment.yml, environment.yml, pyproject.toml, setup.cfg
=> Add Python 3.12 support

geoutils/interface/raster_point.py, geoutils/raster/array.py, geoutils/raster/multiraster.py, geoutils/raster/sampling.py, tests/test_raster/test_array.py, tests/test_raster/test_raster.py
This way they are more easily importable (in xDEM), even though not listed in the API.
We should define a consistent accessibility level for functions depending on their modules.
This is not for users, but for other developers (like xDEM) that might need to rely on lower-level functionalities. So not urgent.
For now only class methods (of `Raster`, `Vector`, etc) are listed in the public API, with a few exceptions.
=> Revert making all `raster.array` non-public

doc/source/raster_class.md, geoutils/raster/raster.py, geoutils/stats.py, tests/test_raster/test_raster.py, tests/test_stats.py
Resolves #602 GlacioHack/xdem#660
This pull request introduces enhancements to the statistics calculation methods in the project. The goal is to provide users with more flexible and comprehensive statistics functionality for raster data. The `get_stats` method has been created to:
- **Return a list of statistics in a dict** containing mean, median, max, mean, sum, sum of squares, 90th percentile, nmad, rmse, std.
- **Support single statistic**: User can request one statistic.
- **Support multiple statistics**: Users can request multiple statistics in one call.
- **Support custom callables**: Users can pass any callable function to calculate custom statistics.
A list of aliases has been drawn up in order to be as flexible as possible when users request statistics.
- **NMAD in …
=> Adding statistics to Raster

geoutils/raster/distributed_computing/cluster.py, tests/test_raster/test_distributing_computing/test_cluster.py
Resolves GlacioHack/xdem#681.
This PR introduces a set of classes designed to handle the execution of tasks in either a basic or a multi-processing cluster. It also includes a series of tests that verify the correct behavior of the cluster functionalities.
- `ClusterGenerator`: A factory class that decides which type of cluster to create based on the given configuration (`basic` or `multiprocessing`). It can initialize a `BasicCluster` or `MpCluster` with a specified number of worker processes.
- `AbstractCluster`: The base class for both `BasicCluster` and `MpCluster`. It defines methods to launch tasks, retrieve results, and manage resources such as opening and closing the cluster.
- `BasicCluster`: A subclass of `AbstractCluster` where tasks are run synchronously (i.e., in a single …
=> Cluster Classes and Testing Implementation

doc/source/api.md, doc/source/raster_class.md, geoutils/raster/raster.py, geoutils/stats.py, tests/conftest.py, tests/test_raster/test_raster.py, tests/test_stats.py
Resolves GlacioHack/xdem#679.
Resolves GlacioHack/xdem#685
- Add `valid points` and `percentage valid points` statistic calculation, as the number of finite values divided by the number of values in the unmasked Raster.
- Add `valid points` and `percentage valid points` in the `dict` returned by `get_stats`, add aliases.
- Add `valid points` and `percentage valid points` in `test_stats` method in `test_raster`.
- Add `valid points no mask` and `percentage valid points no mask` to compute the same stats as above but without masking 
values.
- Add `LE90` in `stats.py` and in `Raster.get_stats`, and test it in `test_stats.py`.
=> Add percentage valid points in `get_stats()`

geoutils/raster/raster.py, tests/test_raster/test_raster.py
Resolves #662.
- Adds robustness in `Percentage_valid_inlier_ points` when `total_inlier_counts` is 0 to avoid divided by 0.
- Sets all stats to `NaN` when the raster or inlier mask is empty and add a warning in logging.
- Fixes `rmse` (the sum was missing).
- Adds a test with an empty inlier mask, ensure returned stats are `NaN`
- Adds a check to ensure that value types in stats are `int` or `float`.
=> Fix `Raster.get_stats` when an empty `inlier_mask` is passed

geoutils/raster/multiraster.py, tests/test_raster/test_multiraster.py
**Bug found with Python 3.12.7**
When a call to `raster/multiraster.merge_rasters()` uses a lambda function as `merge_algorithm` like this:
`merge_algorithm=lambda x: np.logical_and(*x)`
the `TypeError` on unexpected kwarg `axis` is not handled because the error message is different from the hardcoded expected error message structure.
Adds support for this error message structure.
```
File "/home/ehusby/miniforge3/envs/dem-slice/lib/python3.12/site-packages/geoutils/raster/multiraster.py", line 312, in merge_rasters
merged_data.append(algo(raster_stack.data, axis=0))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: my_calling_func.<locals>.<lambda>() got an unexpected keyword argument 'axis'
```
=> Add handling of failure case for `merge_rasters()` `algo` check

geoutils/raster/distributed_computing/cluster.py, geoutils/raster/raster.py, tests/test_raster/test_raster.py
- Adding the profile option to the raster metadata
- "fork" seems to be more widely usable than forkserver (especially on the CNES cluster)
=> Add profile to raster metadata and use fork for multiprocessing  

doc/source/raster_class.md, geoutils/raster/georeferencing.py, geoutils/raster/geotransformations.py, geoutils/raster/raster.py, tests/test_raster/test_geotransformations.py, tests/test_raster/test_raster.py
Resolves #659 
- Changes order of `icrop` bounding box to match with Rasterio.BoundingBox.
- Adds a parameter `distance_unit: Literal["georeferenced", "pixel"] = "georeferenced"` in `georeferencing._crop` to match with the use of `icrop`.
- Updates crop tests.
-  Updates crop section in `raster_class.md`.
=> Optimizing `raster.icrop`

doc/source/multiprocessing.md, geoutils/raster/distributed_computing/__init__.py, geoutils/raster/distributed_computing/multiproc.py, tests/test_raster/test_distributing_computing/test_multiproc.py
Resolves #670.
To enable efficient raster processing on large datasets without exceeding memory limits, this PR introduces generic multiprocessing functions within `geoutils`. These functions allow users to apply any processing function to raster data using a tiling approach with overlap handling. The approach minimizes memory usage by processing tiles separately and writing results directly to disk.
This PR introduces the following key functions:
- `map_overlap_multiproc_save`: This function divides the input raster into overlapping tiles, processes them in parallel using
multiprocessing, and writes the processed results to an output raster file.
- `map_multiproc_collect`: This function splits an input raster into overlapping tiles, processes them in parallel, and returns the results as …
=> Generic Multiprocessing Functions for Raster Processing

.github/workflows/pip-checks.yml, .github/workflows/python-tests.yml, geoutils/examples.py
Moves environment setup to `actions/setup-python` in pip CI.
Removes `distutils` usage, replaced by `shutil`.
(Also fixes a small inconsistency in version usage and run number for Coveralls).
Resolves #674
=> Fix pip CI checks and remove `distutils` implicit dependency

geoutils/raster/georeferencing.py, tests/test_raster/test_raster.py
Somehow we didn't have this covered. Related errors appear more often with new NumPy 2 casting.
=> Add default nodata support for integer 64 types

doc/source/api.md, geoutils/vector/vector.py, tests/test_vector/test_vector.py
The list of non-supported Shapely functions (returned by warnings in our CI) has been growing, so here's an update.
This will be less of a problem once we mirror the `Vector` and `PointCloud` classes by Pandas accessors.
=> Update `Vector` class to latest Shapely functions

geoutils/__init__.py, geoutils/stats.py
Resolves GlacioHack/xdem#715.
- In xDEM usage, the nmad can be use on masked array where nan values are not always masked. In this cases the `np.ma.median` is not working.
- Adding `stats` in `__init__`.
=> Modify `nmad` to match with xDEM usage

geoutils/raster/raster.py, tests/test_raster/test_raster.py, tests/test_raster/test_satimg.py
- Add image structure in tags (`geoutils/geoutils/raster/raster.py`)
- Add tests to save a file in COG format (`tests/test_raster/test_raster.py`) 
Do not check COMPRESSION tags for the following reasons:
The tags of rast and the tags of saved are compared. The file saved has no compression by default (the image is already saved). The tag COMPRESSION is not present in IMAGE_STRUCTURE. The file rast is saved during the test, therefore a compression is applied. The tag COMPRESSION is present in IMAGE_STRUCTURE. Therefore, it is not possible to compare the tag COMPRESSION for both files.
=> Add COG format

geoutils/raster/distributed_computing/multiproc.py, tests/test_raster/test_distributing_computing/test_multiproc.py
When the output of `map_overlap_multiproc_save` is a `Mask`, it is converted to uint8, with a nodata of 255 so that it can be saved via rasterio.
=> Handle Masks in `map_overlap_multiproc_save`

.github/workflows/pip-checks.yml, .github/workflows/python-tests.yml, setup.cfg
It's impossible to flag the warning from pip in CI, so the best solution was to simply automatize the finding of packages, given that anything we have under `geoutils/` is always a package meant to be distributed.
Additionally, `setuptools` was raising a `DeprecationWarning` for using a classifier for the license, saying to remove it and correct the license code with the SPDX identifier: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license.
Resolves #686
=> Use automatic `packages.find` listing to avoid forgetting `setuptools` modules

geoutils/raster/distributed_computing/multiproc.py, geoutils/raster/tiling.py, tests/test_raster/test_tiling.py
- Added error message if the overlap in the tiling is negative/not an integer, added tests.
- Fix error message in `_write_multiproc_result`.
=> Add input checks for tiling

geoutils/vector/vector.py, tests/test_vector/test_vector.py
I remove the wrapper for geom_almost_equal because this function doesn't exist anymore in geopandas
Resolves #700
=> Remove geom_almost_equal from Geopandas

dev-environment.yml, environment.yml, requirements.txt, tests/test_raster/test_distributing_computing/test_dask.py
Has been broken recently in CI, because the base memory fluctuates depending on OS type and runner.
Looks like the new version of Xarray breaks Rioxarray and thus us. 
Need to pin down the max version for now.
Resolves #692
=> Fix Dask memory test for `subsample`

AUTHORS.md, dev-environment.yml, doc/source/raster_class.md, geoutils/raster/raster.py, pyproject.toml, setup.cfg, tests/test_raster/test_multiraster.py, tests/test_raster/test_raster.py
This PR proposes to add the IQR (Interquartile Range) to the statistical information (dict) of a raster.
1. SciPy was choosen over Numpy :
- IQR function is already implemented in scipy.stats ([here](https://docs.scipy.org/doc/scipy-1.16.0/reference/generated/scipy.stats.iqr.html))
- This function is faster than recompute it with Numpy 
```
Numpy) 0.011367651999535155 sec
iqr = 530.6628723144531
Scipy) 0.0081036680003308 sec
iqr = 530.6628723144531 
Numpy) 0.14357674500024586 sec
iqr = 499999.5
Scipy) 0.07437301699974341 sec
iqr = 499999.5 
```
2. The computation no need to be outsourced in another fonction (like others np metrics or rmse at worst).
By the way, it replaces the obsolete pytest-lazyfixture with the new (working with Pytest > 8.0.0 and maintained) variant …
=> Add IQR stat  + pytest correction with lazy_fixtures
