GlacioHack/geoutils

GeoUtils/raster_tools.py

Add steps to __init__ to load the rasterio dataset and copy specific attributes. Add the info method.

Load dataset using rasterio. Add info method.

---

GeoUtils/raster_tools.py
doc/raster-basics.rst

Add __str__ function so that print(myRaster) yields the output of myRaster.info().
myRaster.info() now provides a string (rather than printing directly).
Added a dummy __repr__ function, which definitely needs revisiting once we've fleshed out the rest of the class.

Nicer implementation of info printing, plus some other minor bits

---

GeoUtils/raster_tools.py

Also some pep8/formatting changes.

open dataset as a MemoryFile before reading

---

GeoUtils/raster_tools.py

Add function to save raster to file.

Save to file

---

GeoUtils/raster_tools.py
setup.py

As per the docstring, this uses rioxarray under the hood so that we can generate a 'georeferenced' DataArray.
I've updated setup.py appropriately.

Add to_xarray() method.

---

GeoUtils/raster_tools.py

This method allows to create a Raster from a data array with accompanying transform and CRS information.
To complete this neatly I had to modify __init__ to detect the case when this classmethod is called.
Also, load_data now ==True by default, else this method would not have the desired behaviour. Anyway, I reckon that load_data=True by default is probably more user friendly for most applications ;)

Add a from_array() class method.

---

.gitignore
GeoUtils/proj_tools.py
GeoUtils/raster_tools.py

**Summary**
- add a proj_tool library with functions to handle different projections etc. Need to be common to raster and vector classes
- in proj_tools, add a function to create a Polygon from a bounds
- in Raster, add an intersection method to return the extent of intersection between two rasters
- add Emacs backup files to gitignore
**Left to do**
- handle different CRS
- add a tool to check if two CRS are the same

Add intersection method

---

GeoUtils/proj_tools.py

use `pyproj.CRS.is_exact_same()` to compare CRS objects

add a comparsion between two projections

---

GeoUtils/vector_tools.py

add Vector class init directly with GeoDataFrame

---

.gitignore
GeoUtils/proj_tools.py
GeoUtils/raster_tools.py
GeoUtils/vector_tools.py

- fix a mess up due to conflicts with previous commits/branches. Some changes had been reverted, hence the many commits.
- fix an issue with a missing import

Minor change + some mess up

---

geoutils/georaster.py

Remove checks on non-existent variables

---

geoutils/georaster.py

Fixes #40 .
Previously, this was erroneously being handed off to crop().
Now, if dst_bounds and dst_res provided, then the new raster size is calculated in-method, ensuring that pixel size remains fixed to dst_res. This means that dst_bounds will be adjusted (increased slightly) if it was not already divisible into the requested pixel size.

reproject(): Handle dst_bounds correctly when dst_res provided.

---

geoutils/georaster.py

Fixes a small bug with the Raster.matches_disk flag.

Fix filematch

---

geoutils/projtools.py

fix import for shapely.ops.transform

---

geoutils/georaster.py

Almost identical to georaster's value_at_coords, but using rasterio instead of GDAL.
Also added two options:
- masked: set to True to return a masked array with no data masked
- boundless: set to True to enable windows larger than raster extent
Left to do:
- implement the latlon argument
- possibly enable any input CRS

Add method value_at_coords

---

.github/workflows/python-app.yml
requirements.txt
tests/test_geoutils.py

Set up CI/testing

---

.github/workflows/python-app.yml
.readthedocs.yml
README.md
environment.yml
requirements.txt

I had trouble getting things started today due to lack of an environment file. This environment (and the updated readme instructions) got the tests running for me. I tested on Mac and Linux.
We can update the github actions to using the environment.yml if desired.

environment.yml file for a geoutils environment

---

.github/workflows/python-app.yml
README.md

Update contribution guidelines

---

geoutils/georaster.py
tests/test_georaster.py

Please see #113 for the motivation.

Add __eq__ method and tests

---

geoutils/georaster.py
tests/test_georaster.py

Update raster attributes if downsample is not 1

---

doc/api.rst
geoutils/georaster.py

Improve docs

---

CONTRIBUTING.md

add contributing.md, based on version in xdem

---

geoutils/georaster.py
tests/test_georaster.py

Make sure from_array takes into account input data mask

---

doc/index.rst

Just a test to update the documentation from GitHub directly.

Update documentation index

---

geoutils/georaster.py

`Raster.reproject()` should now be faster as it uses `rio.warp.reproject()` with multiple cores now. I say "should" because it turns out that the single-threaded operation is really fast as well, and I don't have a big raster to benchmark on!!
Solves #177

Enable multithreading for `Raster.reproject()` by default.

---

.github/workflows/python-app.yml
README.md

Badges!!!
The conda-forge install is now up, so this should be the recommended installation procedure.
Also, the README had some outdated text saying "we should get it on readthedocs" (done) and "we need testing" (done, and specified in CONTRIBUTING.md), so I removed those paragraphs. You can see how my suggested frontpage would look here:
https://github.com/erikmannerfelt/GeoUtils/tree/update_readme

Add badges. Changed install recommendation to conda-forge. Remove some old documentation.

---

geoutils/georaster.py
tests/test_georaster.py

Also improve tests to include two rasters with different resolution, which was the reason for not identifying this bug before.
Fixes #198.

Fix bug in reproject with dst_ref. 

---

geoutils/satimg.py
tests/test_satimg.py

All in the name.
To improve reading of tests, etc...

Set SatImg as silent by default

---

CONTRIBUTING.md

This PR resolves #229. But, instead of the preferred fix noted there of creating an additional .yml file describing the dev environment or adding the dev dependencies to environment.yml, I propose simply using pip with the dev-requirements.txt file already in place.
I have also tried to improve the sequencing/readability of the document.

Fix development contribution instructions

---

geoutils/georaster/raster.py
tests/test_georaster.py

This is mostly in reply to issue #273.

Make reproject work even with data not loaded

---

.github/workflows/python-app.yml
dev-environment.yml
dev-requirements.txt
environment.yml
geoutils/misc.py

All in the title
Resolves #296

Check that `environment.yml` can import geoutils, and use diff with `dev-environment.yml` during CI

---

HOW_TO_RELEASE.md

Hello there!
I just updated the conda-forge version.
This process should be automatic but isn't at the moment, so I thought it best to document how an update is done.
Please let me know if I should change or add something.

Add instructions on how to update the conda-forge feedstock

---

tests/test_misc.py

Following comment of @adehecq in GeoUtils (mirrored in xDEM):
https://github.com/GlacioHack/geoutils/pull/314#discussion_r975483816

Fix version check in `misc.test_deprecate`

---

geoutils/georaster/raster.py

Account for @adehecq comment a posteriori: https://github.com/GlacioHack/geoutils/pull/313#discussion_r975422348

Elaborate in `__eq__` docstring

---

geoutils/misc.py

Fix version check in our `deprecate` decorator using `packaging.Version`
Didn't realize this what also an issue in `misc.py` when solving #315

Fix `deprecate` version check

---

doc/source/conf.py
doc/source/core_inheritance.md
doc/source/index.md

Point towards default branch of xDEM documentation

---

geoutils/vector.py
tests/test_vector.py

Return self input in `Vector` class

---

HOW_TO_RELEASE.md
doc/source/how_to_install.md

Following @adehecq's recent comments, ongoing.

Minor a posteriori fixes on recent PRs

---

geoutils/raster/sampling.py
tests/test_sampling.py

Fixing behaviour to match the description of the function, tests adjusted!

Fix subsampling with `subsample` < 1 to be fraction of valid pixels

---

geoutils/projtools.py
tests/test_projtools.py

Improve on #392 after finding new errors with shapely=1.8.5.

Improve backward compatibility for shapely < 2.0

---

.github/workflows/python-publish.yml

Add pip install test during publish

---

.github/workflows/python-publish.yml
.github/workflows/python-tests.yml

Following #416, both filenames and run names were a bit outdated!

Clarify GitHub Action files and run names

---

.github/workflows/python-publish.yml
.github/workflows/python-tests.yml

Mirrors https://github.com/GlacioHack/xdem/pull/411
Some but not all were updated in #413

Update CI action versions

---

.github/workflows/python-publish.yml

Mirrors https://github.com/GlacioHack/xdem/pull/459/

 Pin max Python version for PyPI publish

---

dev-environment.yml
environment.yml
requirements.txt

To reduce warnings and errors related to Pandas/NumPy on latest versions

Allow pandas v2

---

bin/geoviewer.py
doc/source/proj_tools.md
doc/source/quick_start.md
examples/analysis/array_numerics/numpy_interfacing.py
examples/analysis/array_numerics/python_arithmetic.py
examples/analysis/geospatial/buffer_voronoi.py
examples/analysis/geospatial/proximity_metric.py
examples/analysis/point_extraction/interpolation.py
examples/analysis/point_extraction/reduction.py
examples/handling/georeferencing/crop_raster.py
examples/handling/georeferencing/crop_vector.py
examples/handling/georeferencing/reproj_raster.py
examples/handling/georeferencing/reproj_vector.py
examples/handling/interface/create_mask.py
examples/handling/interface/polygonize.py
examples/handling/interface/rasterize.py
examples/handling/interface/topoints.py
examples/io/import_export/from_array.py
examples/io/import_export/import_raster.py
examples/io/import_export/import_vector.py
examples/io/open_save/read_raster.py
examples/io/open_save/read_vector.py
geoutils/raster/raster.py
geoutils/raster/sampling.py
geoutils/vector.py
tests/test_raster.py
tests/test_sampling.py

Refactor `.show()` to `.plot()` and `sample` to `subsample`

---

doc/source/raster_class.md

Replace `indexes` into `bands` in documentation

---

.github/scripts/generate_pip_deps_from_conda.py
requirements.txt

Remove `setuptools` and `setuptools_scm` from requirements.txt

---

dev-environment.yml
environment.yml
requirements.txt

They hopefully fixed the compatibility bugs they had...
Resolves #474

Unfix `geopandas` and `pandas` version

---

geoutils/raster/raster.py
geoutils/vector.py
tests/test_vector.py

Print `Vector.info()` by default

---

geoutils/raster/raster.py
geoutils/vector.py
tests/test_raster/test_raster.py
tests/test_vector.py

Add `.footprint` attribute to `Raster` and `Vector`

---

geoutils/raster/raster.py
tests/test_raster/test_raster.py

Add `data_column_name` argument to `Raster.polygonize`

---

dev-environment.yml

Add Rasterio 1.4 support, and fix OSGeo import

---

.github/workflows/python-tests.yml

Temporarily skip Windows CI

---

.github/workflows/pip-checks.yml
.github/workflows/python-tests.yml

Mirrors https://github.com/GlacioHack/xdem/pull/655

Deprecate Mambaforge for Miniforge

---

geoutils/__init__.py
setup.cfg

I made the same error as in #404, took me a while to find the issue.
I added a section in the Wiki for future reference: https://github.com/GlacioHack/xdem/wiki/Things-to-know-on-Conda%E2%80%90forge

Fix module declaration in `setup.cfg` for conda packaging

---

geoutils/raster/raster.py

Change default plot interpolation to avoid large PDF sizes

---

.github/workflows/pip-checks.yml
.github/workflows/python-tests.yml

See #654 
And also: https://github.com/GlacioHack/xdem/issues/639

Temporary fix to CI breaks

---

geoutils/raster/tiling.py

Fix NumPy integer overflow to get count in `subdivide_array`

---

.github/workflows/pip-checks.yml
.github/workflows/python-tests.yml
CONTRIBUTING.md
dev-environment.yml
environment.yml
setup.cfg

Add back Python 3.10 support

---

examples/handling/raster_point/reduction.py
geoutils/raster/raster.py

5 minutes corrections 
Resolves #722 Resolves  #714 Resolves #709

Fix some typos

---

.github/workflows/python-tests.yml

Unpin `coverage` and convert to LCOV for compatibility with Numba
